#!/bin/bash
if [ $# -gt 0 ]; then
  for PARAM in $*
  do
    case $PARAM in
    -c)
    	ENABLE_COLOR=1
	;;
    esac
  done
fi
if [ `cat /sys/class/power_supply/BAT0/charge_now 2> /dev/null` ]; then
  LEVEL="$(echo `cat /sys/class/power_supply/BAT0/charge_now`*100/`cat /sys/class/power_supply/BAT0/charge_full` | bc)"
else
  LEVEL="XX"
fi
AC=`cat /sys/class/power_supply/AC/online`

if [ $ENABLE_COLOR ]; then
  if [ $AC -eq 0 ]; then
    COLOR="\e[1;31m"
  else
    COLOR="\e[1;32m"
  fi
else
  LEVEL="AC"
fi

if [ $ENABLE_COLOR ]; then
  echo -e "$COLOR$LEVEL\e[0m"
else
  echo $LEVEL
fi
