#!/bin/bash
if [ $# -gt 0 ]; then
  for PARAM in $*
  do
    case $PARAM in
    -c)
    	ENABLE_COLOR=1
	;;
	*)
		echo "tp-batlevel [-c]" 
		"-- Shows current battery level as a percentage. With -c uses color to indicate AC adapter, rather than 'AC'"
		exit 1
	;;
    esac
  done
fi

if [ -e /sys/class/power_supply/BAT0/charge_now ]; then
  LEVEL="$((`cat /sys/class/power_supply/BAT0/charge_now`*100/`cat /sys/class/power_supply/BAT0/charge_full`))"
else
  if [ -e /sys/class/power_supply/BAT0/energy_now ]; then
    LEVEL="$((`cat /sys/class/power_supply/BAT0/energy_now`*100/`cat /sys/class/power_supply/BAT0/energy_full`))"
  else
    LEVEL="XX"
  fi
fi
AC=`cat /sys/class/power_supply/AC/online`

if [ $ENABLE_COLOR ]; then
  if [ $AC -eq 0 ]; then
    COLOR="\e[1;31m"
  else
    COLOR="\e[1;32m"
  fi
else
  if [ $AC -ne 0 ]; then
    LEVEL="AC"
  fi
fi

if [ $ENABLE_COLOR ]; then
  echo -e "$COLOR$LEVEL\e[0m"
else
  echo $LEVEL
fi

