#!/bin/bash
MOUNTS_ROOT=/mnt/ns/

FILE=$PWD

if [ $# -gt 1 ]; then
	echo "Usage: $0 [file]" >&2;
	exit 1;
fi

if [ $# -eq 1 ]; then
	FILE=${PWD}/$1;
fi

CAN_PATH=$(readlink -f "${FILE}")

REL_PATH=${CAN_PATH#`echo $MOUNTS_ROOT`union/}

if [ ! -f ${MOUNTS_ROOT}union/$REL_PATH ]; then
	echo "Invalid filename: $REL_PATH" >&2;
	exit 1;
fi

HOSTS=`ls ${MOUNTS_ROOT}`
for HOST in $HOSTS
do
	if [ $HOST != "union" -a -f ${MOUNTS_ROOT}${HOST}/${REL_PATH} ]; then
		echo "${HOST}";
	fi
done

